/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clue;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.Timer;


/**
 *
 * @author kylin
 */
public class testmap extends javax.swing.JFrame {
    private List<List<Space>> board;
    private Space start_red;
    private Space start_blue;
    private Space test_room;
    private boolean draw_card;
    private Person testPerson;
    private Person testPerson1;
    private Person testPerson2;
    private Border glowBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(0, 191, 255), 3, true),  // Outer glow
                BorderFactory.createEmptyBorder(5, 10, 5, 10)  // Padding
        );
    List<Space> possible;
    private boolean player1;
    private boolean player2;
    /**
     * Creates new form testmap
     */
    public testmap() {
        draw_card = false;
        initComponents();
        cluesheet.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            animateLift(cluesheet, 5, true); // Lift up
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            animateLift(cluesheet, 5, false); // Move back down
        }
        
    });
    cluecards.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseEntered(java.awt.event.MouseEvent evt) {
        animateLift(cluecards, 5, true); // Lift up
    }

    @Override
    public void mouseExited(java.awt.event.MouseEvent evt) {
        animateLift(cluecards, 5, false); // Move back down
    }
    });
        init_board();
        start_game();
        
    }
    
    

private void animateLift(JLabel label, int liftAmount, boolean liftUp) {
    int originalY = label.getY();
    int targetY = liftUp ? originalY - liftAmount : originalY + liftAmount;

    Timer timer = new Timer(10, new java.awt.event.ActionListener() {
        int currentY = label.getY();
        boolean lifting = liftUp;

        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            if (lifting && currentY > targetY) {
                currentY -= 1; // Move up
            } else if (!lifting && currentY < targetY) {
                currentY += 1; // Move down
            } else {
                ((Timer) e.getSource()).stop(); // Stop animation when done
            }
            label.setLocation(label.getX(), currentY);
        }
    });

    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cluecards = new javax.swing.JLabel();
        cluesheet = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        testboard = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cluecards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cluehand.jpg"))); // NOI18N
        getContentPane().add(cluecards, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 120));

        cluesheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cluesheettemplate.png"))); // NOI18N
        cluesheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cluesheetMouseClicked(evt);
            }
        });
        getContentPane().add(cluesheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, -1));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, 70));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 70, 70));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 70, 70));

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 70, 70));

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, 70));

        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 70, 70));

        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 70, 70));

        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, 70));

        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 80, 70));

        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 70, 70));

        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 70, 70));

        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 70, 70));

        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 70, 70));

        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 70, 70));

        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 70, 70));

        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 80));

        jButton17.setBackground(java.awt.Color.red);
        jButton17.setBorderPainted(false);
        jButton17.setDoubleBuffered(true);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 70));

        jButton18.setText("Test Room");
        jButton18.setActionCommand("Test Room 1");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 130, 70));

        testboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/test.png"))); // NOI18N
        getContentPane().add(testboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 320, 320));

        jButton19.setBackground(java.awt.Color.blue);
        jButton19.setBorderPainted(false);
        jButton19.setDoubleBuffered(true);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, 70));

        Reset.setText("Reset Position");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int curr_row = 3;
        int curr_col = 4;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int curr_row = 2;
        int curr_col = 3;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int curr_row = 1;
        int curr_col = 1;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int curr_row = 1;
        int curr_col = 2;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int curr_row = 1;
        int curr_col = 3;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int curr_row = 1;
        int curr_col = 4;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int curr_row = 0;
        int curr_col = 1;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int  curr_row = 0;
        int curr_col = 2;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int curr_row = 0;
        int curr_col = 3;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int curr_row = 0;
        int curr_col = 4;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int curr_row = 2;
        int curr_col = 1;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int curr_row = 2;
        int curr_col = 2;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int curr_row = 2;
        int curr_col = 4;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int curr_row = 3;
        int curr_col = 1;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       int curr_row = 3;
       int  curr_col = 3;
       Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       int  curr_row = 3;
        int curr_col = 2;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       int curr_row = 1;
       int  curr_col = 5;
        Space curr_space = board.get(curr_row).get(curr_col);
        if ((!curr_space.isOccupied()||curr_space.getOccupant()==testPerson) && possible.contains(board.get(curr_row).get(curr_col))) {
            move_piece(board.get(curr_row).get(curr_col));
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void cluesheetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cluesheetMouseClicked
        new testsheet().setVisible(true);
    }//GEN-LAST:event_cluesheetMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Space curr1 = testPerson1.getCurrSpace();
        Space curr2 = testPerson2.getCurrSpace();
        curr1.setOccupant(null);
        curr2.setOccupant(null);
        curr1.setOccupied(false);
        curr2.setOccupied(false);
        start_red.setOccupant(testPerson1);
        start_red.setOccupied(true);
        start_blue.setOccupant(testPerson2);
        start_blue.setOccupied(true);
        testPerson1.setCurrSpace(start_red);
        testPerson2.setCurrSpace(start_blue);
        unset_selectable();
        int roll = maingamehelpers.dice_roll();
        possible = maingamehelpers.get_available(board, testPerson.getCurrSpace().getRow(), testPerson.getCurrSpace().getCol(), 4, 6, roll);
        set_selectable();
    }//GEN-LAST:event_ResetActionPerformed

    public void init_board() {
        board = new ArrayList<>();
        JButton[][] buttons = {
            {null, jButton1, jButton2, jButton3, jButton4, null},
            {jButton17, jButton5, jButton6, jButton7, jButton8, jButton18},
            {jButton19,jButton9, jButton10, jButton11, jButton12, null},
            {null,jButton13, jButton14, jButton15, jButton16, null}
        };
        
        for (int row = 0; row < 4; row++) {
            List<Space> rowSpaces = new ArrayList<>();
            for (int col = 0; col < 6; col++) {
                JButton curr = buttons[row][col];
                if (curr == null) {
                    rowSpaces.add(null);
                }
                else if (curr == jButton17) {
                    start_red = new Space(curr, false, row, col);
                    rowSpaces.add(start_red);
                }
                else if (curr == jButton18) {
                    test_room = new Space(curr, true, row, col);
                    rowSpaces.add(test_room);
                }
                else if (curr == jButton19) {
                    start_blue = new Space(curr, false, row, col);
                    rowSpaces.add(start_blue);
                }
                else {
                rowSpaces.add(new Space(curr, false, row, col));
                }
            }
            board.add(rowSpaces);
        }
        
    }
    
    public void move_piece(Space next_space){
        Space currSpace = testPerson.getCurrSpace();
        currSpace.setOccupied(false);
        currSpace.setOccupant(null);
        next_space.setOccupant(testPerson);
        next_space.setOccupied(true);
        testPerson.setCurrSpace(next_space);
        unset_selectable();
        next_game();
    }
    
    public void start_game() {
        testPerson1 = new Person(Color.red, "test person", start_red);
        testPerson2 = new Person(Color.blue, "test person", start_blue);
        testPerson = testPerson1;
        start_red.setOccupant(testPerson1);
        start_red.setOccupied(true);
        start_blue.setOccupant(testPerson2);
        start_blue.setOccupied(true);
        int curr_roll = maingamehelpers.dice_roll();
        possible = maingamehelpers.get_available(board, testPerson.getCurrSpace().getRow(), testPerson.getCurrSpace().getCol(), 4, 6, curr_roll);
        set_selectable();
        
    }
    
    public void accuse_player(Person accused, Space Room, String Weapon) {
        Space current = accused.getCurrSpace();
        current.setOccupant(null);
        current.setOccupied(false);
        Room.setOccupant(accused);
        Room.setOccupied(true);
    }
    
    public void next_game() {
        int curr_roll = maingamehelpers.dice_roll();
        set_turn();
        possible = maingamehelpers.get_available(board, testPerson.getCurrSpace().getRow(), testPerson.getCurrSpace().getCol(), 4, 6, curr_roll);
        set_selectable();
        
    }
    
    public void set_turn() {
        if (testPerson == testPerson1) {
            testPerson = testPerson2;
        }
        else{
            testPerson = testPerson1;
        }
    } 
    
    public void set_selectable() {
        for (Space reachable: possible) {
            if (reachable != null && reachable.getButton() != null) {
            // Reset the border first
            if (!reachable.isOccupied()){
            reachable.getButton().setBorder(null);
            reachable.getButton().setBorder(glowBorder); // Apply the new border
            }
        }
        }
        this.revalidate();
        this.repaint();
    }
    
    public void unset_selectable() {
        for (Space reachable: possible) {
            reachable.getButton().setBorder(null);
        }
        this.revalidate();
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testmap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JLabel cluecards;
    private javax.swing.JLabel cluesheet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel testboard;
    // End of variables declaration//GEN-END:variables
}
